{{- $configmapname := .Values.configmapname }}
{{- $secretname    := .Values.secretname    }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}-app
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-app
    spec:
      containers:
      - env:
          {{- range .Values.variables.configmap }}
          - name: {{ .name }}
            valueFrom:
              configMapKeyRef:
                name: {{ $configmapname }}
                key: {{ .name }}
          {{- end }}
          {{- range .Values.variables.secret }}
          - name: {{ .name }}
            valueFrom:
              secretKeyRef:
                name: {{ $secretname }}
                key: {{ .name }}
          {{- end }}
        image: {{ .Values.image }}
        imagePullPolicy: Always
        name: {{ .Values.name }}
        ports:
        - containerPort: 80
          name: internal
          protocol: TCP
      restartPolicy: Always

