apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}-app
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-app
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: Always
        name: {{ .Values.name }}
        ports:
        - containerPort: {{ .Values.port }}
          name: internal
          protocol: TCP
      restartPolicy: Always

